
CREATE TABLE CUSTOMER (
    CUSTOMER_ID NUMBER PRIMARY KEY,
    NAME VARCHAR2(50),
    AGE NUMBER,
    BALANCE NUMBER(10,2),
    ISVIP VARCHAR2(5)
);

CREATE TABLE LOAN (
    LOAN_ID NUMBER PRIMARY KEY,
    CUSTOMER_ID NUMBER,
    INTEREST_RATE NUMBER(5,2),
    DUE_DATE DATE,
    CONSTRAINT FK_CUSTOMER
        FOREIGN KEY (CUSTOMER_ID)
        REFERENCES CUSTOMER(CUSTOMER_ID)
);

INSERT INTO CUSTOMER VALUES (1, 'Ravi', 65, 15000, 'FALSE');
INSERT INTO CUSTOMER VALUES (2, 'Sita', 45, 8000, 'FALSE');
INSERT INTO CUSTOMER VALUES (3, 'Arjun', 70, 25000, 'FALSE');
INSERT INTO CUSTOMER VALUES (4, 'Priya', 30, 12000, 'FALSE');

INSERT INTO LOAN VALUES (101, 1, 10, SYSDATE + 15);
INSERT INTO LOAN VALUES (102, 2, 11, SYSDATE + 40);
INSERT INTO LOAN VALUES (103, 3, 9, SYSDATE + 20);
INSERT INTO LOAN VALUES (104, 4, 12, SYSDATE + 10);

COMMIT;
